/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as InvoiceTokenRouteImport } from './routes/invoice/$token'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppProductStockRouteImport } from './routes/_app/product-stock'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppOutboundRouteImport } from './routes/_app/outbound'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppMetricsRouteImport } from './routes/_app/metrics'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppIntegrationRouteImport } from './routes/_app/integration'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppHandoverRouteImport } from './routes/_app/handover'
import { Route as AppFlowsRouteImport } from './routes/_app/flows'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppBroadcastRouteImport } from './routes/_app/broadcast'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAiAgentsRouteImport } from './routes/_app/ai-agents'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppDevelopersIndexRouteImport } from './routes/_app/developers/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppAppsIndexRouteImport } from './routes/_app/apps/index'
import { Route as AppFlowsFlowIdRouteImport } from './routes/_app/flows/$flowId'
import { Route as AppDevelopersWebhooksRouteImport } from './routes/_app/developers/webhooks'
import { Route as AppDevelopersMessagesSentByApiRouteImport } from './routes/_app/developers/messages-sent-by-api'
import { Route as AppDevelopersApiToolsRouteImport } from './routes/_app/developers/api-tools'
import { Route as AppDevelopersApiDocumentationRouteImport } from './routes/_app/developers/api-documentation'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers/$customerId'
import { Route as AppConversationsConversationIdRouteImport } from './routes/_app/conversations/$conversationId'
import { Route as AppChannelsWhatsappRouteImport } from './routes/_app/channels/whatsapp'
import { Route as AppChannelsTelegramRouteImport } from './routes/_app/channels/telegram'
import { Route as AppChannelsLivechatRouteImport } from './routes/_app/channels/livechat'
import { Route as AppChannelsLineRouteImport } from './routes/_app/channels/line'
import { Route as AppChannelsFacebookRouteImport } from './routes/_app/channels/facebook'
import { Route as AppChannelsCustomRouteImport } from './routes/_app/channels/custom'
import { Route as AppChannelsBotRouteImport } from './routes/_app/channels/bot'
import { Route as AppAppsMetaAdsTrackerRouteImport } from './routes/_app/apps/meta-ads-tracker'
import { Route as AppAppsAppSlugRouteImport } from './routes/_app/apps/$appSlug'
import { Route as AppAiAgentsAgentIdRouteImport } from './routes/_app/ai-agents/$agentId'
import { Route as AppDevelopersApiToolsNewRouteImport } from './routes/_app/developers/api-tools/new'
import { Route as AppChannelsWhatsappSuccessRouteImport } from './routes/_app/channels/whatsapp/success'
import { Route as AppChannelsWhatsappChannelIdRouteImport } from './routes/_app/channels/whatsapp/$channelId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceTokenRoute = InvoiceTokenRouteImport.update({
  id: '/invoice/$token',
  path: '/invoice/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProductStockRoute = AppProductStockRouteImport.update({
  id: '/product-stock',
  path: '/product-stock',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppOutboundRoute = AppOutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationRoute = AppIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppHandoverRoute = AppHandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsRoute = AppFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastRoute = AppBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAgentsRoute = AppAiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersIndexRoute = AppDevelopersIndexRouteImport.update({
  id: '/developers/',
  path: '/developers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsIndexRoute = AppAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsFlowIdRoute = AppFlowsFlowIdRouteImport.update({
  id: '/$flowId',
  path: '/$flowId',
  getParentRoute: () => AppFlowsRoute,
} as any)
const AppDevelopersWebhooksRoute = AppDevelopersWebhooksRouteImport.update({
  id: '/developers/webhooks',
  path: '/developers/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersMessagesSentByApiRoute =
  AppDevelopersMessagesSentByApiRouteImport.update({
    id: '/developers/messages-sent-by-api',
    path: '/developers/messages-sent-by-api',
    getParentRoute: () => AppRoute,
  } as any)
const AppDevelopersApiToolsRoute = AppDevelopersApiToolsRouteImport.update({
  id: '/developers/api-tools',
  path: '/developers/api-tools',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersApiDocumentationRoute =
  AppDevelopersApiDocumentationRouteImport.update({
    id: '/developers/api-documentation',
    path: '/developers/api-documentation',
    getParentRoute: () => AppRoute,
  } as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsConversationIdRoute =
  AppConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppChannelsWhatsappRoute = AppChannelsWhatsappRouteImport.update({
  id: '/channels/whatsapp',
  path: '/channels/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsTelegramRoute = AppChannelsTelegramRouteImport.update({
  id: '/channels/telegram',
  path: '/channels/telegram',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsLivechatRoute = AppChannelsLivechatRouteImport.update({
  id: '/channels/livechat',
  path: '/channels/livechat',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsLineRoute = AppChannelsLineRouteImport.update({
  id: '/channels/line',
  path: '/channels/line',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsFacebookRoute = AppChannelsFacebookRouteImport.update({
  id: '/channels/facebook',
  path: '/channels/facebook',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsCustomRoute = AppChannelsCustomRouteImport.update({
  id: '/channels/custom',
  path: '/channels/custom',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsBotRoute = AppChannelsBotRouteImport.update({
  id: '/channels/bot',
  path: '/channels/bot',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsMetaAdsTrackerRoute = AppAppsMetaAdsTrackerRouteImport.update({
  id: '/apps/meta-ads-tracker',
  path: '/apps/meta-ads-tracker',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsAppSlugRoute = AppAppsAppSlugRouteImport.update({
  id: '/apps/$appSlug',
  path: '/apps/$appSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAgentsAgentIdRoute = AppAiAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AppAiAgentsRoute,
} as any)
const AppDevelopersApiToolsNewRoute =
  AppDevelopersApiToolsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppDevelopersApiToolsRoute,
  } as any)
const AppChannelsWhatsappSuccessRoute =
  AppChannelsWhatsappSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AppChannelsWhatsappRoute,
  } as any)
const AppChannelsWhatsappChannelIdRoute =
  AppChannelsWhatsappChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AppChannelsWhatsappRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AppAiRoute
  '/ai-agents': typeof AppAiAgentsRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/broadcast': typeof AppBroadcastRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/flows': typeof AppFlowsRouteWithChildren
  '/handover': typeof AppHandoverRoute
  '/help': typeof AppHelpRoute
  '/integration': typeof AppIntegrationRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/metrics': typeof AppMetricsRoute
  '/orders': typeof AppOrdersRoute
  '/outbound': typeof AppOutboundRoute
  '/pipeline': typeof AppPipelineRoute
  '/product-stock': typeof AppProductStockRoute
  '/products': typeof AppProductsRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/templates': typeof AppTemplatesRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/ai-agents/$agentId': typeof AppAiAgentsAgentIdRoute
  '/apps/$appSlug': typeof AppAppsAppSlugRoute
  '/apps/meta-ads-tracker': typeof AppAppsMetaAdsTrackerRoute
  '/channels/bot': typeof AppChannelsBotRoute
  '/channels/custom': typeof AppChannelsCustomRoute
  '/channels/facebook': typeof AppChannelsFacebookRoute
  '/channels/line': typeof AppChannelsLineRoute
  '/channels/livechat': typeof AppChannelsLivechatRoute
  '/channels/telegram': typeof AppChannelsTelegramRoute
  '/channels/whatsapp': typeof AppChannelsWhatsappRouteWithChildren
  '/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/developers/api-documentation': typeof AppDevelopersApiDocumentationRoute
  '/developers/api-tools': typeof AppDevelopersApiToolsRouteWithChildren
  '/developers/messages-sent-by-api': typeof AppDevelopersMessagesSentByApiRoute
  '/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/apps/': typeof AppAppsIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/developers/': typeof AppDevelopersIndexRoute
  '/channels/whatsapp/$channelId': typeof AppChannelsWhatsappChannelIdRoute
  '/channels/whatsapp/success': typeof AppChannelsWhatsappSuccessRoute
  '/developers/api-tools/new': typeof AppDevelopersApiToolsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AppAiRoute
  '/ai-agents': typeof AppAiAgentsRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/broadcast': typeof AppBroadcastRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/flows': typeof AppFlowsRouteWithChildren
  '/handover': typeof AppHandoverRoute
  '/help': typeof AppHelpRoute
  '/integration': typeof AppIntegrationRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/metrics': typeof AppMetricsRoute
  '/orders': typeof AppOrdersRoute
  '/outbound': typeof AppOutboundRoute
  '/pipeline': typeof AppPipelineRoute
  '/product-stock': typeof AppProductStockRoute
  '/products': typeof AppProductsRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/templates': typeof AppTemplatesRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/ai-agents/$agentId': typeof AppAiAgentsAgentIdRoute
  '/apps/$appSlug': typeof AppAppsAppSlugRoute
  '/apps/meta-ads-tracker': typeof AppAppsMetaAdsTrackerRoute
  '/channels/bot': typeof AppChannelsBotRoute
  '/channels/custom': typeof AppChannelsCustomRoute
  '/channels/facebook': typeof AppChannelsFacebookRoute
  '/channels/line': typeof AppChannelsLineRoute
  '/channels/livechat': typeof AppChannelsLivechatRoute
  '/channels/telegram': typeof AppChannelsTelegramRoute
  '/channels/whatsapp': typeof AppChannelsWhatsappRouteWithChildren
  '/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/developers/api-documentation': typeof AppDevelopersApiDocumentationRoute
  '/developers/api-tools': typeof AppDevelopersApiToolsRouteWithChildren
  '/developers/messages-sent-by-api': typeof AppDevelopersMessagesSentByApiRoute
  '/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/apps': typeof AppAppsIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/developers': typeof AppDevelopersIndexRoute
  '/channels/whatsapp/$channelId': typeof AppChannelsWhatsappChannelIdRoute
  '/channels/whatsapp/success': typeof AppChannelsWhatsappSuccessRoute
  '/developers/api-tools/new': typeof AppDevelopersApiToolsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/ai-agents': typeof AppAiAgentsRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/broadcast': typeof AppBroadcastRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/flows': typeof AppFlowsRouteWithChildren
  '/_app/handover': typeof AppHandoverRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/integration': typeof AppIntegrationRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/outbound': typeof AppOutboundRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/product-stock': typeof AppProductStockRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/_app/ai-agents/$agentId': typeof AppAiAgentsAgentIdRoute
  '/_app/apps/$appSlug': typeof AppAppsAppSlugRoute
  '/_app/apps/meta-ads-tracker': typeof AppAppsMetaAdsTrackerRoute
  '/_app/channels/bot': typeof AppChannelsBotRoute
  '/_app/channels/custom': typeof AppChannelsCustomRoute
  '/_app/channels/facebook': typeof AppChannelsFacebookRoute
  '/_app/channels/line': typeof AppChannelsLineRoute
  '/_app/channels/livechat': typeof AppChannelsLivechatRoute
  '/_app/channels/telegram': typeof AppChannelsTelegramRoute
  '/_app/channels/whatsapp': typeof AppChannelsWhatsappRouteWithChildren
  '/_app/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/developers/api-documentation': typeof AppDevelopersApiDocumentationRoute
  '/_app/developers/api-tools': typeof AppDevelopersApiToolsRouteWithChildren
  '/_app/developers/messages-sent-by-api': typeof AppDevelopersMessagesSentByApiRoute
  '/_app/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/_app/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/_app/apps/': typeof AppAppsIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/developers/': typeof AppDevelopersIndexRoute
  '/_app/channels/whatsapp/$channelId': typeof AppChannelsWhatsappChannelIdRoute
  '/_app/channels/whatsapp/success': typeof AppChannelsWhatsappSuccessRoute
  '/_app/developers/api-tools/new': typeof AppDevelopersApiToolsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/ai'
    | '/ai-agents'
    | '/analytics'
    | '/broadcast'
    | '/chat'
    | '/dashboard'
    | '/flows'
    | '/handover'
    | '/help'
    | '/integration'
    | '/knowledge'
    | '/metrics'
    | '/orders'
    | '/outbound'
    | '/pipeline'
    | '/product-stock'
    | '/products'
    | '/settings'
    | '/team'
    | '/templates'
    | '/invoice/$token'
    | '/payment/success'
    | '/ai-agents/$agentId'
    | '/apps/$appSlug'
    | '/apps/meta-ads-tracker'
    | '/channels/bot'
    | '/channels/custom'
    | '/channels/facebook'
    | '/channels/line'
    | '/channels/livechat'
    | '/channels/telegram'
    | '/channels/whatsapp'
    | '/conversations/$conversationId'
    | '/customers/$customerId'
    | '/developers/api-documentation'
    | '/developers/api-tools'
    | '/developers/messages-sent-by-api'
    | '/developers/webhooks'
    | '/flows/$flowId'
    | '/apps/'
    | '/customers/'
    | '/developers/'
    | '/channels/whatsapp/$channelId'
    | '/channels/whatsapp/success'
    | '/developers/api-tools/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/ai'
    | '/ai-agents'
    | '/analytics'
    | '/broadcast'
    | '/chat'
    | '/dashboard'
    | '/flows'
    | '/handover'
    | '/help'
    | '/integration'
    | '/knowledge'
    | '/metrics'
    | '/orders'
    | '/outbound'
    | '/pipeline'
    | '/product-stock'
    | '/products'
    | '/settings'
    | '/team'
    | '/templates'
    | '/invoice/$token'
    | '/payment/success'
    | '/ai-agents/$agentId'
    | '/apps/$appSlug'
    | '/apps/meta-ads-tracker'
    | '/channels/bot'
    | '/channels/custom'
    | '/channels/facebook'
    | '/channels/line'
    | '/channels/livechat'
    | '/channels/telegram'
    | '/channels/whatsapp'
    | '/conversations/$conversationId'
    | '/customers/$customerId'
    | '/developers/api-documentation'
    | '/developers/api-tools'
    | '/developers/messages-sent-by-api'
    | '/developers/webhooks'
    | '/flows/$flowId'
    | '/apps'
    | '/customers'
    | '/developers'
    | '/channels/whatsapp/$channelId'
    | '/channels/whatsapp/success'
    | '/developers/api-tools/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/_app/ai'
    | '/_app/ai-agents'
    | '/_app/analytics'
    | '/_app/broadcast'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/flows'
    | '/_app/handover'
    | '/_app/help'
    | '/_app/integration'
    | '/_app/knowledge'
    | '/_app/metrics'
    | '/_app/orders'
    | '/_app/outbound'
    | '/_app/pipeline'
    | '/_app/product-stock'
    | '/_app/products'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/templates'
    | '/invoice/$token'
    | '/payment/success'
    | '/_app/ai-agents/$agentId'
    | '/_app/apps/$appSlug'
    | '/_app/apps/meta-ads-tracker'
    | '/_app/channels/bot'
    | '/_app/channels/custom'
    | '/_app/channels/facebook'
    | '/_app/channels/line'
    | '/_app/channels/livechat'
    | '/_app/channels/telegram'
    | '/_app/channels/whatsapp'
    | '/_app/conversations/$conversationId'
    | '/_app/customers/$customerId'
    | '/_app/developers/api-documentation'
    | '/_app/developers/api-tools'
    | '/_app/developers/messages-sent-by-api'
    | '/_app/developers/webhooks'
    | '/_app/flows/$flowId'
    | '/_app/apps/'
    | '/_app/customers/'
    | '/_app/developers/'
    | '/_app/channels/whatsapp/$channelId'
    | '/_app/channels/whatsapp/success'
    | '/_app/developers/api-tools/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  InvoiceTokenRoute: typeof InvoiceTokenRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$token': {
      id: '/invoice/$token'
      path: '/invoice/$token'
      fullPath: '/invoice/$token'
      preLoaderRoute: typeof InvoiceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/product-stock': {
      id: '/_app/product-stock'
      path: '/product-stock'
      fullPath: '/product-stock'
      preLoaderRoute: typeof AppProductStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outbound': {
      id: '/_app/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof AppOutboundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integration': {
      id: '/_app/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AppIntegrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/handover': {
      id: '/_app/handover'
      path: '/handover'
      fullPath: '/handover'
      preLoaderRoute: typeof AppHandoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows': {
      id: '/_app/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof AppFlowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcast': {
      id: '/_app/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof AppBroadcastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-agents': {
      id: '/_app/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AppAiAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/': {
      id: '/_app/developers/'
      path: '/developers'
      fullPath: '/developers/'
      preLoaderRoute: typeof AppDevelopersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/': {
      id: '/_app/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppAppsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows/$flowId': {
      id: '/_app/flows/$flowId'
      path: '/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof AppFlowsFlowIdRouteImport
      parentRoute: typeof AppFlowsRoute
    }
    '/_app/developers/webhooks': {
      id: '/_app/developers/webhooks'
      path: '/developers/webhooks'
      fullPath: '/developers/webhooks'
      preLoaderRoute: typeof AppDevelopersWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/messages-sent-by-api': {
      id: '/_app/developers/messages-sent-by-api'
      path: '/developers/messages-sent-by-api'
      fullPath: '/developers/messages-sent-by-api'
      preLoaderRoute: typeof AppDevelopersMessagesSentByApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/api-tools': {
      id: '/_app/developers/api-tools'
      path: '/developers/api-tools'
      fullPath: '/developers/api-tools'
      preLoaderRoute: typeof AppDevelopersApiToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/api-documentation': {
      id: '/_app/developers/api-documentation'
      path: '/developers/api-documentation'
      fullPath: '/developers/api-documentation'
      preLoaderRoute: typeof AppDevelopersApiDocumentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations/$conversationId': {
      id: '/_app/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof AppConversationsConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/whatsapp': {
      id: '/_app/channels/whatsapp'
      path: '/channels/whatsapp'
      fullPath: '/channels/whatsapp'
      preLoaderRoute: typeof AppChannelsWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/telegram': {
      id: '/_app/channels/telegram'
      path: '/channels/telegram'
      fullPath: '/channels/telegram'
      preLoaderRoute: typeof AppChannelsTelegramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/livechat': {
      id: '/_app/channels/livechat'
      path: '/channels/livechat'
      fullPath: '/channels/livechat'
      preLoaderRoute: typeof AppChannelsLivechatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/line': {
      id: '/_app/channels/line'
      path: '/channels/line'
      fullPath: '/channels/line'
      preLoaderRoute: typeof AppChannelsLineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/facebook': {
      id: '/_app/channels/facebook'
      path: '/channels/facebook'
      fullPath: '/channels/facebook'
      preLoaderRoute: typeof AppChannelsFacebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/custom': {
      id: '/_app/channels/custom'
      path: '/channels/custom'
      fullPath: '/channels/custom'
      preLoaderRoute: typeof AppChannelsCustomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/bot': {
      id: '/_app/channels/bot'
      path: '/channels/bot'
      fullPath: '/channels/bot'
      preLoaderRoute: typeof AppChannelsBotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/meta-ads-tracker': {
      id: '/_app/apps/meta-ads-tracker'
      path: '/apps/meta-ads-tracker'
      fullPath: '/apps/meta-ads-tracker'
      preLoaderRoute: typeof AppAppsMetaAdsTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/$appSlug': {
      id: '/_app/apps/$appSlug'
      path: '/apps/$appSlug'
      fullPath: '/apps/$appSlug'
      preLoaderRoute: typeof AppAppsAppSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-agents/$agentId': {
      id: '/_app/ai-agents/$agentId'
      path: '/$agentId'
      fullPath: '/ai-agents/$agentId'
      preLoaderRoute: typeof AppAiAgentsAgentIdRouteImport
      parentRoute: typeof AppAiAgentsRoute
    }
    '/_app/developers/api-tools/new': {
      id: '/_app/developers/api-tools/new'
      path: '/new'
      fullPath: '/developers/api-tools/new'
      preLoaderRoute: typeof AppDevelopersApiToolsNewRouteImport
      parentRoute: typeof AppDevelopersApiToolsRoute
    }
    '/_app/channels/whatsapp/success': {
      id: '/_app/channels/whatsapp/success'
      path: '/success'
      fullPath: '/channels/whatsapp/success'
      preLoaderRoute: typeof AppChannelsWhatsappSuccessRouteImport
      parentRoute: typeof AppChannelsWhatsappRoute
    }
    '/_app/channels/whatsapp/$channelId': {
      id: '/_app/channels/whatsapp/$channelId'
      path: '/$channelId'
      fullPath: '/channels/whatsapp/$channelId'
      preLoaderRoute: typeof AppChannelsWhatsappChannelIdRouteImport
      parentRoute: typeof AppChannelsWhatsappRoute
    }
  }
}

interface AppAiAgentsRouteChildren {
  AppAiAgentsAgentIdRoute: typeof AppAiAgentsAgentIdRoute
}

const AppAiAgentsRouteChildren: AppAiAgentsRouteChildren = {
  AppAiAgentsAgentIdRoute: AppAiAgentsAgentIdRoute,
}

const AppAiAgentsRouteWithChildren = AppAiAgentsRoute._addFileChildren(
  AppAiAgentsRouteChildren,
)

interface AppFlowsRouteChildren {
  AppFlowsFlowIdRoute: typeof AppFlowsFlowIdRoute
}

const AppFlowsRouteChildren: AppFlowsRouteChildren = {
  AppFlowsFlowIdRoute: AppFlowsFlowIdRoute,
}

const AppFlowsRouteWithChildren = AppFlowsRoute._addFileChildren(
  AppFlowsRouteChildren,
)

interface AppChannelsWhatsappRouteChildren {
  AppChannelsWhatsappChannelIdRoute: typeof AppChannelsWhatsappChannelIdRoute
  AppChannelsWhatsappSuccessRoute: typeof AppChannelsWhatsappSuccessRoute
}

const AppChannelsWhatsappRouteChildren: AppChannelsWhatsappRouteChildren = {
  AppChannelsWhatsappChannelIdRoute: AppChannelsWhatsappChannelIdRoute,
  AppChannelsWhatsappSuccessRoute: AppChannelsWhatsappSuccessRoute,
}

const AppChannelsWhatsappRouteWithChildren =
  AppChannelsWhatsappRoute._addFileChildren(AppChannelsWhatsappRouteChildren)

interface AppDevelopersApiToolsRouteChildren {
  AppDevelopersApiToolsNewRoute: typeof AppDevelopersApiToolsNewRoute
}

const AppDevelopersApiToolsRouteChildren: AppDevelopersApiToolsRouteChildren = {
  AppDevelopersApiToolsNewRoute: AppDevelopersApiToolsNewRoute,
}

const AppDevelopersApiToolsRouteWithChildren =
  AppDevelopersApiToolsRoute._addFileChildren(
    AppDevelopersApiToolsRouteChildren,
  )

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAiAgentsRoute: typeof AppAiAgentsRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBroadcastRoute: typeof AppBroadcastRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFlowsRoute: typeof AppFlowsRouteWithChildren
  AppHandoverRoute: typeof AppHandoverRoute
  AppHelpRoute: typeof AppHelpRoute
  AppIntegrationRoute: typeof AppIntegrationRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppOutboundRoute: typeof AppOutboundRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppProductStockRoute: typeof AppProductStockRoute
  AppProductsRoute: typeof AppProductsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppAppsAppSlugRoute: typeof AppAppsAppSlugRoute
  AppAppsMetaAdsTrackerRoute: typeof AppAppsMetaAdsTrackerRoute
  AppChannelsBotRoute: typeof AppChannelsBotRoute
  AppChannelsCustomRoute: typeof AppChannelsCustomRoute
  AppChannelsFacebookRoute: typeof AppChannelsFacebookRoute
  AppChannelsLineRoute: typeof AppChannelsLineRoute
  AppChannelsLivechatRoute: typeof AppChannelsLivechatRoute
  AppChannelsTelegramRoute: typeof AppChannelsTelegramRoute
  AppChannelsWhatsappRoute: typeof AppChannelsWhatsappRouteWithChildren
  AppConversationsConversationIdRoute: typeof AppConversationsConversationIdRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppDevelopersApiDocumentationRoute: typeof AppDevelopersApiDocumentationRoute
  AppDevelopersApiToolsRoute: typeof AppDevelopersApiToolsRouteWithChildren
  AppDevelopersMessagesSentByApiRoute: typeof AppDevelopersMessagesSentByApiRoute
  AppDevelopersWebhooksRoute: typeof AppDevelopersWebhooksRoute
  AppAppsIndexRoute: typeof AppAppsIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDevelopersIndexRoute: typeof AppDevelopersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAiAgentsRoute: AppAiAgentsRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBroadcastRoute: AppBroadcastRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFlowsRoute: AppFlowsRouteWithChildren,
  AppHandoverRoute: AppHandoverRoute,
  AppHelpRoute: AppHelpRoute,
  AppIntegrationRoute: AppIntegrationRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppOutboundRoute: AppOutboundRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppProductStockRoute: AppProductStockRoute,
  AppProductsRoute: AppProductsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppAppsAppSlugRoute: AppAppsAppSlugRoute,
  AppAppsMetaAdsTrackerRoute: AppAppsMetaAdsTrackerRoute,
  AppChannelsBotRoute: AppChannelsBotRoute,
  AppChannelsCustomRoute: AppChannelsCustomRoute,
  AppChannelsFacebookRoute: AppChannelsFacebookRoute,
  AppChannelsLineRoute: AppChannelsLineRoute,
  AppChannelsLivechatRoute: AppChannelsLivechatRoute,
  AppChannelsTelegramRoute: AppChannelsTelegramRoute,
  AppChannelsWhatsappRoute: AppChannelsWhatsappRouteWithChildren,
  AppConversationsConversationIdRoute: AppConversationsConversationIdRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppDevelopersApiDocumentationRoute: AppDevelopersApiDocumentationRoute,
  AppDevelopersApiToolsRoute: AppDevelopersApiToolsRouteWithChildren,
  AppDevelopersMessagesSentByApiRoute: AppDevelopersMessagesSentByApiRoute,
  AppDevelopersWebhooksRoute: AppDevelopersWebhooksRoute,
  AppAppsIndexRoute: AppAppsIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDevelopersIndexRoute: AppDevelopersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  InvoiceTokenRoute: InvoiceTokenRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
